name: 'Terraform GitHub Actions'
on:
  pull_request:
    branches:
      - master

jobs:
  fmt:
    name: 'terraform fmt'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2.3.4

      - name: 'Terraform Format'
        uses: 'clouddrove/github-actions@v6.0'
        with:
          actions_subcommand: 'fmt'

  Basic:
    name: 'Init,Validate,PLan of Basic example'
    needs: fmt
    runs-on: ubuntu-latest
    steps:

      - name: 'Checkout'
        uses: actions/checkout@v2.3.4

      - name: 'Configure AWS Credentials'
        uses: clouddrove/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.TEST_AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.TEST_AWS_ACCESS_SECRET_KEY }}
          aws-region: us-east-2

      - name: 'Terraform init'
        uses: 'clouddrove/github-actions@v6.0'
        with:
          actions_subcommand: 'init'
          tf_actions_working_dir: ./_example/basic

      - name: 'Terraform validate'
        uses: 'clouddrove/github-actions@v6.0'
        with:
          actions_subcommand: 'validate'
          tf_actions_working_dir: ./_example/basic

      - name: 'Terraform plan'
        uses: 'clouddrove/github-actions@v6.0'
        with:
          actions_subcommand: 'plan'
          tf_actions_working_dir: ./_example/basic
